#!/bin/bash
# Install Persona Native Messaging host for Chrome/Chromium browsers
#
# Usage:
#   ./install-native-host.sh [EXTENSION_ID]
#
# The script will:
#   1. Detect the persona CLI binary location
#   2. Create the native messaging host manifest
#   3. Install it to the appropriate location for your OS
#
# Note: Run this script after installing the Persona CLI.

set -e

EXTENSION_ID="${1:-}"
HOST_NAME="com.persona.native"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Detect OS
detect_os() {
    case "$(uname -s)" in
        Darwin*)  echo "macos" ;;
        Linux*)   echo "linux" ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
        *)        error "Unsupported OS: $(uname -s)" ;;
    esac
}

# Find persona binary
find_persona_binary() {
    local binary=""

    # Check common locations
    if command -v persona &> /dev/null; then
        binary="$(command -v persona)"
    elif [ -f "/usr/local/bin/persona" ]; then
        binary="/usr/local/bin/persona"
    elif [ -f "$HOME/.cargo/bin/persona" ]; then
        binary="$HOME/.cargo/bin/persona"
    elif [ -f "/opt/homebrew/bin/persona" ]; then
        binary="/opt/homebrew/bin/persona"
    fi

    if [ -z "$binary" ]; then
        error "Could not find persona binary. Please ensure it's installed and in your PATH."
    fi

    # Return absolute path
    echo "$(cd "$(dirname "$binary")" && pwd)/$(basename "$binary")"
}

# Get manifest directory for the OS
get_manifest_dir() {
    local os="$1"
    local browser="$2"

    case "$os" in
        macos)
            case "$browser" in
                chrome)
                    echo "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
                    ;;
                chromium)
                    echo "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
                    ;;
                brave)
                    echo "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts"
                    ;;
                edge)
                    echo "$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
                    ;;
            esac
            ;;
        linux)
            case "$browser" in
                chrome)
                    echo "$HOME/.config/google-chrome/NativeMessagingHosts"
                    ;;
                chromium)
                    echo "$HOME/.config/chromium/NativeMessagingHosts"
                    ;;
                brave)
                    echo "$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
                    ;;
                edge)
                    echo "$HOME/.config/microsoft-edge/NativeMessagingHosts"
                    ;;
            esac
            ;;
    esac
}

# Create manifest JSON
create_manifest() {
    local binary_path="$1"
    local extension_id="$2"

    if [ -z "$extension_id" ]; then
        error "Extension ID is required (find it at chrome://extensions and re-run: $0 <EXTENSION_ID>)"
    fi

    local allowed_origins="[\"chrome-extension://${extension_id}/\"]"

    cat << EOF
{
  "name": "${HOST_NAME}",
  "description": "Persona Password Manager Native Messaging Bridge",
  "path": "${binary_path}",
  "type": "stdio",
  "allowed_origins": ${allowed_origins}
}
EOF
}

# Main installation
main() {
    local os=$(detect_os)
    info "Detected OS: $os"

    if [ -z "$EXTENSION_ID" ]; then
        error "Missing EXTENSION_ID. Usage: $0 <EXTENSION_ID>"
    fi

    local binary=$(find_persona_binary)
    info "Found persona binary: $binary"

    # Verify it has the bridge subcommand
    if ! "$binary" bridge --help &> /dev/null; then
        error "The persona binary does not support the 'bridge' command. Please update to the latest version."
    fi

    # Create wrapper script that invokes 'persona bridge'
    local wrapper_dir="$HOME/.persona/bin"
    local wrapper_path="$wrapper_dir/persona-bridge"

    mkdir -p "$wrapper_dir"

    cat > "$wrapper_path" << EOF
#!/bin/bash
# Persona Native Messaging Bridge Wrapper
# Auto-generated by install-native-host.sh
exec "${binary}" bridge "\$@"
EOF

    chmod +x "$wrapper_path"
    info "Created bridge wrapper: $wrapper_path"

    # Generate manifest
    local manifest=$(create_manifest "$wrapper_path" "$EXTENSION_ID")

    # Install for each supported browser
    local browsers=("chrome" "chromium" "brave" "edge")
    local installed=0

    for browser in "${browsers[@]}"; do
        local manifest_dir=$(get_manifest_dir "$os" "$browser")
        if [ -n "$manifest_dir" ]; then
            mkdir -p "$manifest_dir"
            local manifest_file="${manifest_dir}/${HOST_NAME}.json"
            echo "$manifest" > "$manifest_file"
            info "Installed manifest for $browser: $manifest_file"
            ((installed++))
        fi
    done

    if [ $installed -eq 0 ]; then
        error "Could not install manifest for any browser"
    fi

    echo ""
    info "✅ Native messaging host installed successfully!"
    echo ""
    echo "Next steps:"
    echo "  1. Install the Persona browser extension"
    echo "  2. Open the extension popup and use the Pairing section"
    echo ""
    echo "To test the bridge manually:"
    echo "  python3 - <<'PY' | \"$wrapper_path\""
    echo "import json, struct, sys"
    echo "msg = {\"type\": \"status\", \"payload\": {}}"
    echo "data = json.dumps(msg).encode('utf-8')"
    echo "sys.stdout.buffer.write(struct.pack('<I', len(data)))"
    echo "sys.stdout.buffer.write(data)"
    echo "PY"
}

main "$@"
